# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE=moveit.rosinstall
    # moveit_ros_perception: mesh_filter_test fails due to broken Mesa OpenGL
    - TEST_BLACKLIST="moveit_ros_perception"
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-function"
    - WARNINGS_OK=false
    - CCACHE_SLOPPINESS="include_file_ctime,include_file_mtime"
    - CCACHE_MAXSIZE=20G
  matrix:
    - TEST="code-coverage"
      TEST_WHITELIST="moveit moveit_commander moveit_core moveit_kinematics moveit_ros_visualization moveit_runtime moveit_setup_assistant moveit_simple_controller_manager"
    - TEST="code-coverage"
      TEST_WHITELIST="chomp_motion_planner moveit_chomp_optimizer_adapter moveit_planners moveit_ros_move_group moveit_ros_manipulation moveit_ros_robot_interaction moveit_ros_warehouse moveit_ros_benchmarks moveit_ros_planning_interface moveit_planners_chomp moveit_planners_ompl moveit_planners_trajopt"
    - TEST="code-coverage"
      TEST_WHITELIST="moveit_plugins moveit_ros moveit_ros_occupancy_map_monitor moveit_ros_planning moveit_fake_controller_manager moveit_ros_control_interface moveit_jog_arm"
    - TEST="clang-format catkin_lint"
    - ROS_DISTRO=melodic
    - ROS_DISTRO=kinetic

matrix: # Add a separate config to the matrix, using clang as compiler
  include:
    # add a config to the matrix using clang as compiler and also test ikfast plugin creation
    - compiler: clang
      env: ROS_REPO=ros-shadow-fixed
           TEST=clang-tidy-fix
           BEFORE_DOCKER_SCRIPT="source moveit_kinematics/test/test_ikfast_plugins.sh"
           CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-function -Wno-overloaded-virtual"

before_script:
  - git clone -q --depth=1 -b p/tylerjw/codecov https://github.com/picknikrobotics/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
